language: cpp

matrix:
  include:
  - os: linux
    name: "MPI-Linux SMP"
    dist: xenial
    script:
    - sudo apt-get update && sudo apt-get install -y mpich libmpich-dev
    - ./build LIBS mpi-linux-x86_64 smp -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla || exit 1
    - make -C mpi-linux-x86_64-smp/tmp -j3 all-test-tests all-test-examples OPTS="-g"
    - make -C mpi-linux-x86_64-smp/tmp test-tests test-examples TESTOPTS="+setcpuaffinity"

  - os: osx
    name: "NetLRTS-Darwin"
    script:
    - ./build LIBS netlrts-darwin-x86_64 -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla || exit 1
    - make -C netlrts-darwin-x86_64/tmp -j3 all-test-tests all-test-examples OPTS="-g"
    - make -C netlrts-darwin-x86_64/tmp test-tests test-examples TESTOPTS="++local"

  - os: windows
    name: "NetLRTS-Win GCC"
    script:
    - ls "/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/"
    - export VCINSTALLDIR="/cygdrive/C/Program Files (x86)/Microsoft Visual Studio 14.0/VC"
    - $mingw64 ./build all-test netlrts-win-x86_64 -j3 --without-romio --with-production --enable-error-checking --enable-lbuserdata -g || exit 1
    - $mingw64 make -C netlrts-win-x86_64-gcc/tmp -j3 all-test-tests all-test-examples OPTS="-g"
    - $mingw64 make -C netlrts-win-x86_64-gcc/tmp test-tests test-examples TESTOPTS="++local"
