version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  NetLRTS:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      - run:
          name: Build
          command: ./build LIBS netlrts-linux-x86_64 -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla
      - run:
          name: Test
          command: make -C netlrts-linux-x86_64/tmp -j3 all-test-tests all-test-examples OPTS="-g" &&  make -C netlrts-linux-x86_64/tmp test-tests test-examples TESTOPTS="++local +isomalloc_sync"
 
  NetLRTS-smp:
    machine:
      image: ubuntu-1604:201903-01
    
    steps:
      - checkout
      - run:
          name: Build
          command: ./build LIBS netlrts-linux-x86_64 smp -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla
      - run:
          name: Test
          command: make -C netlrts-linux-x86_64-smp/tmp -j3 all-test-tests all-test-examples OPTS="-g" && make -C netlrts-linux-x86_64-smp/tmp test-tests test-examples TESTOPTS="++local +setcpuaffinity +isomalloc_sync +CmiSleepOnIdle"
 
 
  winbuild:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: automake
          command: autoconf --version
          shell: bash.exe
    
workflows:
  version: 2
  build:
    jobs:
      - winbuild
