name: Autobuild

on:
  schedule:
    - cron: '01 05 * * *' # UTC, corresponds to 00:01 CDT

jobs:
  might:
# netlrts-linux-x86_64-smp:might.cs.illinois.edu::/scratch/autobuild/netlrts-linux-x86_64-smp:::--with-production --enable-error-checking -j4 -k::++local +CmiSleepOnIdle ::-k:
    timeout-minutes: 120

    runs-on: might
    name: Ubuntu Linux 16.04 x86_64 GCC 5.4.0 NetLRTS SMP

    steps:
    - uses: actions/checkout@v2
      with:
        ref: autobuild
    - name: build
      run: |
        ./build all-test netlrts-linux-x86_64 smp -g -j4 --with-production --enable-error-checking
        export TESTOPTS="++local +CmiSleepOnIdle"
    - name: test
      run: make -C tests test
    - name: testp P=2
      run: make -C tests testp P=2
    - name: testp P=3
      run: make -C tests testp P=3
    - name: examples
      run: make -C examples test
    - name: benchmarks
      run: make -C benchmarks test
