name: Autobuild

on:
  schedule:
    # Run the build as part of a fixed nightly schedule
    - cron: '15 06 * * *' # UTC 6:15am, corresponds to 00:15 CST or 01:15 CDT
  push:
    paths:
      # Also run the build when this file gets modified as part of a PR
      - '.github/workflows/autobuild.yml'
      - '.github/workflows/delta-sbatch-slurm.sh'


# Cancel in progress CI runs when a new run targeting the same PR or branch/tag is triggered.
# https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  Delta:
    timeout-minutes: 60

    runs-on: delta
    name: Delta mpi-linux-x86_64  # Could test various builds (e.g., MPI, UCX, ...) via a build matrix

    steps:
    - uses: actions/checkout@v3
    - name: Host info
      run: |
        set -x
        echo "Running autobuild on delta"
        hostname
        uname -a
        lsb_release -a
        pwd
    - name: build
      run: |
        set -ex
        export target="mpi-linux-x86_64"
        .github/workflows/jobmonitor.sh .github/workflows/delta-sbatch-slurm.sh
    - name: results
      run: |
        # this is incorrect now:
        ## cat ~/autobuild/messages/mpi-linux-x86_64
        # Could add email notification here, e.g. via https://github.com/marketplace/actions/send-email
