name: NetLRTS Linux CMake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./buildcmake LIBS netlrts-linux-x86_64 -g -j4 --with-production
    - name: test
      run: make -C netlrts-linux-x86_64/test OPTS="-g" TESTOPTS="++local +isomalloc_sync"
