name: Sphinx-doc

# Check if documentation builds with sphinx. Only triggered if a file
# in doc/ is changed.

on:
  pull_request:
    paths: 
      - 'doc/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: sphinx
      run: |
        pip3 install sphinx sphinx_rtd_theme
        cd doc
        make html
