name: Multicore Darwin tracing

on: [push]

jobs:
  build:
    timeout-minutes: 60

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./build all-test multicore-darwin-x86_64 -g -j3 --with-production --enable-tracing --enable-tracing-commthread
    - name: test
      run: |
        make -C multicore-darwin-x86_64/tests all -j3 OPTS="-tracemode projections"
        make -C multicore-darwin-x86_64/tests test
        make -C multicore-darwin-x86_64/examples all -j3 OPTS="-tracemode projections"
        make -C multicore-darwin-x86_64/examples test
        make -C multicore-darwin-x86_64/benchmarks all -j3 OPTS="-tracemode projections"
        make -C multicore-darwin-x86_64/benchmarks test
