name: NetLRTS Windows

on: pull_request

jobs:
  build:
    timeout-minutes: 90

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake autoconf automake make
    - name: build
      run: |
        . src/arch/win/vsenv.sh
        ./build AMPI netlrts-win-x86_64 --with-production -j3 -g || ( cat netlrts-win-x86_64/tmp/hwloc/config.log ; exit 1 )
    - name: test
      run: |
        . src/arch/win/vsenv.sh
        make -C netlrts-win-x86_64/tests OPTS="-g" -j3
        make -C netlrts-win-x86_64/tests test TESTOPTS="++local"
