name: UTH Linux

on: [push]

jobs:
  build:
    timeout-minutes: 45

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      run: ./build all-test uth-linux-x86_64 -g -j4 --with-production
    - name: test
      run: |
        make -C uth-linux-x86_64/tests test
        make -C uth-linux-x86_64/examples test
        make -C uth-linux-x86_64/benchmarks test
    - name: testp P=2
      run: |
        make -C uth-linux-x86_64/tests testp P=2
        make -C uth-linux-x86_64/examples testp P=2
        make -C uth-linux-x86_64/benchmarks testp P=2
