name: NetLRTS TCP Windows

on: pull_request

jobs:
  build:
    timeout-minutes: 90

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: git mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool mingw-w64-x86_64-cmake make libtool autoconf automake
    - name: build
      run: |
        . src/arch/win/vsenv.sh
        ./build AMPI netlrts-win-x86_64 tcp --with-production -j2 -g
        make -C netlrts-win-x86_64-tcp/tests OPTS="-g" -j2
    - name: test
      run: |
        make -C netlrts-win-x86_64-tcp/tests test TESTOPTS="++local +setcpuaffinity"
